/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-03 11:29:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1641195078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>카페 | 메일 | News | 로그인 | 회원가입</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/filmlog/boardIndex.css\">   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("            <div class=\"containerIn\">\r\n");
      out.write("                <section class=\"slide\">\r\n");
      out.write("                    <div class=\"slide-img\">\r\n");
      out.write("                        슬라이드\r\n");
      out.write("                        <!-- <img src=\"./img/slide.PNG\" alt=\"\"> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <div class=\"contents\">\r\n");
      out.write("                    <h3>자유게시판</h3>\r\n");
      out.write("                    <div class=\"btn_m\"><a href=\"#\">수정</a></div>\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>제목 입니다.</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"writer\">\r\n");
      out.write("                                <span>작성자 : 한국인 </span>\r\n");
      out.write("                                <span class=\"w_r\">등록일 : 2020-12-25 20:00</span>\r\n");
      out.write("                                <span class=\"w_rr\">조회수 : 100</span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"con\">\r\n");
      out.write("                            <td>\r\n");
      out.write("                                내용Sed ut perspiciatis, unde omnis iste natus error s dkkdasd\r\n");
      out.write("                                it voluptatem accusantium doloremque laudantium, totam rem \r\n");
      out.write("                                aperiam eaque ipsa, quae ab illo inventore veritatis et quasi\r\n");
      out.write("                                architecto beatae vitae dicta sunt, explicabo. Nemo\r\n");
      out.write("                                enim ipsam voluptatem, quia voluptas sit, aspernatur aut \r\n");
      out.write("                                odit aut fugit, sed quia consequuntur magni dolores eos, qui \r\n");
      out.write("                                ratione voluptatem sequi nesciunt, neque porro quisquam est, \r\n");
      out.write("                                qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng]\r\n");
      out.write("                                velit, sed quia non numquam [do] eius modi tempora inci[di]dunt,\r\n");
      out.write("                                ut labore et dolore magnam aliquam quaerat voluptatem. Ut\r\n");
      out.write("                                enim ad minima veniam, quis nostrum[d] exercitationem ullam \r\n");
      out.write("                                corporis suscipit laboriosam, nisi ut aliquid ex ea commodi \r\n");
      out.write("                                consequatur? [D]Quis autem vel eum iure reprehenderit, qui \r\n");
      out.write("                                in ea voluptate velit esse, quam nihil molestiae consequatur,\r\n");
      out.write("                                vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? \r\n");
      out.write("                                [33] At vero eos et accusamus et iusto odio dignissimos ducimus,\r\n");
      out.write("                                qui blanditiis praesentium voluptatum deleniti atque corrupti, \r\n");
      out.write("                                quos dolores et quas molestias excepturi sint, obcaecati \r\n");
      out.write("                                cupiditate non provident, similique sunt in culpa, qui officia \r\n");
      out.write("                                deserunt mollitia animi, id est laborum et dolorum fuga. Et harum \r\n");
      out.write("                                quidem rerum facilis est et expedita distinctio. Nam libero \r\n");
      out.write("                                tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, \r\n");
      out.write("                                quo minus id, quod maxime placeat, facere possimus, omnis \r\n");
      out.write("                                voluptas assumenda est, omnis dolor repellendus. Temporibus \r\n");
      out.write("                                autem quibusdam et aut officiis debitis aut rerum \r\n");
      out.write("                                necessitatibus saepe eveniet, ut et voluptates repudiandae\r\n");
      out.write("                                sint et molestiae non recusandae. Itaque earum rerum hic \r\n");
      out.write("                                tenetur a sapiente delectus, ut aut reiciendis voluptatibus \r\n");
      out.write("                                maiores alias consequatur aut perferendis doloribus asperiores \r\n");
      out.write("                                repellat.\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div class=\"btn\">\r\n");
      out.write("                        <div class=\"btn_r\"><a href=\"writeIndex.html\">글쓰기</a></div>\r\n");
      out.write("                        <div class=\"btn_l\"><a href=\"#\">목록보기</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"beforeAfter\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <span class=\"ba_l\">이전글</span>\r\n");
      out.write("                                    <span class=\"ba_r\">뭐시기 뭐시기 뭐시기</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <span class=\"ba_l\">다음글</span>\r\n");
      out.write("                                    <span class=\"ba_r\">요시기 요시기 요시기</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!--containerIn-->\r\n");
      out.write("        </div> <!--#container-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
